name: Build Docker, Generate Syft SBOM, Run Semgrep & GitLeaks

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for GitLeaks

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t juice-shop .

      

      - name: Install GitLeaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_*_linux_x64.tar.gz
          tar -xzf gitleaks_*_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks secrets scan
        run: gitleaks detect --source . --report-format json --report-path gitleaks-results.json || true

    

      

      - name: Upload GitLeaks results
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results
          path: gitleaks-results.json
        if: always()
