name: Build Docker, Generate Syft SBOM & Run Semgrep

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t juice-shop .

     

      - name: Run Semgrep SAST scan
        run: |
          pip install semgrep
          semgrep --config=auto --json --output=semgrep-results.json . || true

      

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json
        if: always()
